### ISSUE TITLE
Low resolution in iMac 27" retina display

### ISSUE THREAD

**Issue by mcheung63** [markiewb/nb-codeoutline#21]
Low resolution in iMac 27" retina display
<img width="2560" alt="2015-10-17 10 27 25" src="https://cloud.githubusercontent.com/assets/1779905/10559234/5ec0944a-751e-11e5-8185-a18862e366b3.png">

**Comment by markiewb** [comment]
A) Please try http://bluej.org/ . If it works there, then I will integrate their new code in this plugin for it. File an issue there.
B) Or provide a pull-request. Which would help the users of this plugin AND bluej.

----- Ursprungligt meddelande -----
Från: "Peter" <notifications@github.com>
Skickat: ‎17.‎10.‎2015 16:28
Till: "markiewb/nb-codeoutline" <nb-codeoutline@noreply.github.com>
Ämne: [nb-codeoutline] Low resolution in iMac 27" retina display (#21)

Low resolution in iMac 27" retina display

**Comment by mcheung63** [comment]
Hi, i don’t understand why it related to bluej?

**Comment by markiewb** [comment]
BlueJ implemented it as a Swing component. Because NetBeans is also Swing-based, I could integrate it into a NetBeans plugin.

----- Ursprungligt meddelande -----
Från: "Peter" <notifications@github.com>
Skickat: ‎18.‎10.‎2015 05:41
Till: "markiewb/nb-codeoutline" <nb-codeoutline@noreply.github.com>
Kopia: "markiewb" <benno.markiewicz@googlemail.com>
Ämne: Re: [nb-codeoutline] Low resolution in iMac 27" retina display (#21)

Hi, i don’t understand why it related to bluej?

**Comment by markiewb** [comment]
Try out the new version 1.3.0. There you can configure the fontsize
